In [25]:
import cv2
import os
import keras
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from PIL import Image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('dark_background')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [26]:
path=os.listdir('/content/drive/MyDrive/Psoriasis123')
classes={'YES':1,'NO':0}

In [27]:
X=[]
Y=[]
for i in classes:
  path1='/content/drive/MyDrive/Psoriasis123/'+i
  for j in os.listdir(path1):
    img=cv2.imread(path1+'/'+j,0)
    img=cv2.resize(img,(128,128))
    img= cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
    X.append(img)
    Y.append(classes[i])

In [28]:
X=np.array(X)
Y=np.array(Y)


In [29]:
print(X)

[[[[  7   7   7]
   [  8   8   8]
   [  8   8   8]
   ...
   [154 154 154]
   [155 155 155]
   [157 157 157]]

  [[  7   7   7]
   [  8   8   8]
   [  8   8   8]
   ...
   [157 157 157]
   [157 157 157]
   [157 157 157]]

  [[  7   7   7]
   [  8   8   8]
   [  8   8   8]
   ...
   [161 161 161]
   [166 166 166]
   [168 168 168]]

  ...

  [[  7   7   7]
   [  7   7   7]
   [  7   7   7]
   ...
   [135 135 135]
   [134 134 134]
   [124 124 124]]

  [[  7   7   7]
   [  7   7   7]
   [  7   7   7]
   ...
   [131 131 131]
   [139 139 139]
   [125 125 125]]

  [[  7   7   7]
   [  7   7   7]
   [  7   7   7]
   ...
   [136 136 136]
   [120 120 120]
   [127 127 127]]]


 [[[ 16  16  16]
   [ 16  16  16]
   [ 16  16  16]
   ...
   [ 16  16  16]
   [ 15  15  15]
   [ 15  15  15]]

  [[ 16  16  16]
   [ 16  16  16]
   [ 16  16  16]
   ...
   [ 16  16  16]
   [ 16  16  16]
   [ 16  16  16]]

  [[ 16  16  16]
   [ 16  16  16]
   [ 16  16  16]
   ...
   [ 16  16  16]
   [ 15  15  15]
   [ 15  15

In [30]:
print(Y)

[1 1 1 ... 0 0 0]


In [31]:
X = X.reshape((2806, 128, 128, 3))

In [32]:
X.shape

(2806, 128, 128, 3)

In [43]:
Y = np.array(Y)
Y=Y.reshape(1403,2)
Y.shape

(1403, 2)

In [35]:
num_samples_X = X.shape[0]
num_samples_Y = Y.shape[0]

# If the number of samples is inconsistent, you can either:
# 1. Trim the larger dataset to match the smaller one
if num_samples_X > num_samples_Y:
    X = X[:num_samples_Y]
elif num_samples_X < num_samples_Y:
    Y = Y[:num_samples_X]

In [44]:
X.shape

(1403, 128, 128, 3)

In [45]:
Y.shape

(1403, 2)

In [46]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(2, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()
model.fit(X, Y, epochs=10, batch_size=32, validation_split=0.2)  # You need to provide X and Y data here


Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_16 (Conv2D)          (None, 126, 126, 32)      896       
                                                                 
 max_pooling2d_8 (MaxPoolin  (None, 63, 63, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_17 (Conv2D)          (None, 61, 61, 64)        18496     
                                                                 
 max_pooling2d_9 (MaxPoolin  (None, 30, 30, 64)        0         
 g2D)                                                            
                                                                 
 conv2d_18 (Conv2D)          (None, 28, 28, 128)       73856     
                                                                 
 max_pooling2d_10 (MaxPooli  (None, 14, 14, 128)      


YOLOv8 Classification

In [49]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)))
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())

model.add(Dense(128, activation='relu'))
model.add(Dense(2, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X, Y, epochs=10, batch_size=32, validation_split=0.2)


Epoch 1/10
36/36 [==============================] - 44s 1s/step - loss: 3376.2595 - accuracy: 0.5258 - val_loss: 0.0000e+00 - val_accuracy: 0.0214
Epoch 2/10
36/36 [==============================] - 37s 1s/step - loss: 605134.1250 - accuracy: 0.5330 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 3/10
36/36 [==============================] - 38s 1s/step - loss: 16708478.0000 - accuracy: 0.4938 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 4/10
36/36 [==============================] - 36s 1s/step - loss: 85571320.0000 - accuracy: 0.5071 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 5/10
36/36 [==============================] - 38s 1s/step - loss: 666231680.0000 - accuracy: 0.5143 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 6/10
36/36 [==============================] - 36s 1s/step - loss: 3111173120.0000 - accuracy: 0.4581 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 7/10
36/36 [==============================] - 40s 1s/step - loss: 543081932

ResNet 32

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, BatchNormalization, Activation, Add, AveragePooling2D, Flatten, Dense
from tensorflow.keras.models import Model

# Define the Residual Block
def residual_block(x, filters, stride=1):
    shortcut = x
    x = Conv2D(filters, (3, 3), strides=stride, padding='same')(x)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    # Second convolution layer
    x = Conv2D(filters, (3, 3), padding='same')(x)
    x = BatchNormalization()(x)

    # If the input shape and output shape don't match, use a 1x1 convolution for the shortcut
    if stride != 1 or shortcut.shape[-1] != filters:
        shortcut = Conv2D(filters, (1, 1), strides=stride)(shortcut)

    # Add the shortcut to the main path
    x = Add()([x, shortcut])
    x = Activation('relu')(x)
    return x

# Define the ResNet-32 model
def resnet32(input_shape, num_classes):
    inputs = Input(shape=input_shape)

    x = Conv2D(32, (3, 3), padding='same')(inputs)
    x = BatchNormalization()(x)
    x = Activation('relu')(x)

    # Stack of residual blocks
    num_blocks_list = [5, 5, 5]
    for num_blocks in num_blocks_list:
        for _ in range(num_blocks):
            x = residual_block(x, 32)

    # Global Average Pooling
    x = AveragePooling2D(pool_size=(8, 8))(x)

    # Fully connected layer
    x = Flatten()(x)
    x = Dense(num_classes, activation='softmax')(x)

    # Create the model
    model = Model(inputs, x)
    return model

# Create the ResNet-32 model
model = resnet32(input_shape=(128, 128, 3), num_classes=2)

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Print the model summary
model.summary()

# Train the model using X and Y
model.fit(X, Y, epochs=10, batch_size=32, validation_split=0.2)


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 128, 128, 3)]        0         []                            
                                                                                                  
 conv2d_22 (Conv2D)          (None, 128, 128, 32)         896       ['input_1[0][0]']             
                                                                                                  
 batch_normalization_8 (Bat  (None, 128, 128, 32)         128       ['conv2d_22[0][0]']           
 chNormalization)                                                                                 
                                                                                                  
 activation (Activation)     (None, 128, 128, 32)         0         ['batch_normalization_8[0]

Vision Transformer